version: '3'
services:
  app:
    container_name: stock-opt-app
    image: stock-opt-app:latest
    ports:
      - "8050:8050"
    networks:
      - app-network
    environment:
      - OPENAI_API_KEY=1

networks:
  app-network:
    driver: bridge